### ISSUE TITLE
Review CSExplore related work

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/csexplore#1]
The [CSExplore Resources Page](https://radgrad.github.io/docs/csexplore/resources) has a list of papers and websites related to high school CS resources. 

Read these papers, and then write an essay for your professional portfolio that provides:

 * A review of these resources. How can the ideas in these resources help CSExplore?
* How will CSExplore be better/different? Given that CSExplore will be integrated with RadGrad, what will CSExplore be able to do that these systems can't?
* When the essay is published, provide a link to it as a comment to this issue. And please post the link to #summer-startup in RadGrad2 Slack.

**Comment by qauchida** [comment]
Here is the link to my review of the resources for CSExplore: 
https://qauchida.github.io/essays/CSExploreResources.html

**Comment by angeli-amascual** [comment]
Here is a link to my essay: https://angeli-amascual.github.io/essays/potential-csexplore.html

**Comment by maxdeyo** [comment]
Here's my essay: https://maxdeyo.github.io/essays/reviewingCSExploreResources.html

**Comment by ghost** [comment]
https://hannaparkuh.github.io/essays/CSExplore.html
