### ISSUE TITLE
Review native app frameworks

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/csexplore#3]
There are a variety of cross-platfrom frameworks we could use to build CSExplore: NativeScript, React Native, and Flutter being a few of the contenders.  Perhaps you will find additional possibilities.  Note that the RadGrad project is currently based on Javascript/Typescript.  We would like to stay with one of those languages unless a third language offers really compelling benefits. 

Do some reading on native app frameworks and write an essay for your professional portfolio that presents your findings and recommendations for CSExplore.  When finished, post your essay as a link in a comment to this issue. And please post the link to #summer-startup in RadGrad2 Slack.

**Comment by maxdeyo** [comment]
Here's a link to my essay: https://maxdeyo.github.io/essays/comparingAppFrameworks.html

**Comment by qauchida** [comment]
Here's my essay on frameworks: https://qauchida.github.io/essays/frameworkReview.html

**Comment by angeli-amascual** [comment]
Here's a link to my frameworks essay: https://angeli-amascual.github.io/essays/frameworks-csexplore.html

**Comment by ghost** [comment]
https://hannaparkuh.github.io/essays/AppFrameworks.html
