### ISSUE TITLE
Add resources to CSExplore resource page

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/csexplore#4]
Look for relevant readings, and add to https://radgrad.github.io/docs/csexplore/resources

This task will require you to download the RadGrad Summer 2020 docusaurus repo, edit the file, run the system locally to ensure your modifications are OK, then deploy it, as well as commit your changes to the docusaurus2 repo. See https://radgrad.github.io/docs/overview/managing-this-site

This task is not only helpful for generating additional useful resources, it's also good for getting you ready to contribute documentation.

When you're done, add a comment to this issue summarizing what resources you added.

**Comment by angeli-amascual** [comment]
The resources I've added are CodeHS, Computer Science for All in SF, The Beauty and Joy of Computing, and Teaching Kids Programming. In the resources page, I've added a one-line summary of each resource. They are all different sites that promote teaching computer science/programming to students.

**Comment by qauchida** [comment]
I added the State of Hawaii's DOE requirments for STEM senior capstone projects. I also created a new section for local organizations and Hackathons. In the new section, I put the homepage of Stem Works Hawaii, a local organization that promotes STEM education, primarily to public schools on Hawaii island, Maui, Kauai, Molokai, Lanai and Oahu. Stem Works organizes events and various "camps" to teach students various aspects of STEM, including Computer Science.

I've added the Twitter for Kaiser High School's Computer Science club. This was one of the only public schools I could find with a link to anything Computer Science related. I know that other schools have CS classes, but I haven't been able to find any references for that online. 

I've added a link for a robotics organizations in Hawaii. While robotics is not CS specific and usually made up of students wanting to be engineers, major competitions like FIRST Robotics Regionals need student programmers. When I was in high school, FIRST was how I got introduced to the possibility of a career in technology and we could access an untapped demographic of students. Also, it teaches teamwork and could be a good way for students with programming skills to work with others from different disciplines.

Finally, I added the AT&T Hackathon for Hawaii, which has a high school category.

**Comment by maxdeyo** [comment]
I added Code with Google which has resources and CS curriculum's through Google. I also added Code for Life which is another curriculum for students/teachers. I also added a post from Computer Science Online which has a lot of good resources for teaching pre-college students and good info on college prep with coding. I also added Commonsense.org's resource page which has good info on different teaching methods. Finally I added a page from the Hawaii DOE on their methods and intentions with teaching CS for K-12.

**Comment by ghost** [comment]
I added the following websites to the resource page.

**1. Code Wars** - This website challenges users to achieve code mastery which is called "kata". The ranking type is based on some martial arts degree type style. Users earn ranks and honor for completing kata. The theme "martial art" is a creative way to approach reach young users. "Hawaiian culture", "Ocean" and "Surfing" could be interesting themes for CSExplore. 

**2. Kahoot** - This is one of the most popular online learning websites. Kahoot is a game-based learning platform which makes it fun to learn. It would be a good idea that CSExplore creates code challenges, games, or quizzes every month using Kahoot and rewards winners. 

**3. STEM Scouts** - This is a national pilot program from the Boy Scouts which focuses on learning about STEM. It is important to learn how to build relationships and build teamwork at a young age. 
Joining a group and doing a project together can be a great learning experience. CSExplore could provide an online platform which helps high school students to organize CS clubs. 

**4. State fact sheet from code.org** - This fact sheet provides general information about Computer Education in Hawaii. The data in this document shows why we need an online application such as CSExplore for high school students in Hawaii. I was surprised to know that only 47% of public high schools teach a foundational computer science course. We need to provide more resources and opportunities for high school student who are interested in CS.
